Fix #2373 - Correct misc panics with `skycoin-cli` command argument handling
skycoin/skycoin pull request #2374
Opened 2019-05-31 10:07 UTC by BigOokie

Fixes #2373
Changes:
- Correct panic in lastBlocks and checkdb command argument handling

Does this change need to mentioned in CHANGELOG.md?
Yes. Included in PR

2019-05-31 10:26 UTC, therealssj approved these changes

2019-05-31 12:57 UTC, gz-c requested changes
Changelog entry is in the wrong block of text

2019-05-31 13:10 UTC, BigOokie commented
Thanks for calling that out. Will take a look at some point over the weekend and correct. Thanks

2019-06-03 08:20 UTC, BigOokie commented
@gz-c @therealssj I have corrected the issue with the changelog. Thanks again for pointing that out.

2019-06-03 12:11 UTC, merged